### ISSUE TITLE
Open Webconsole in subdomain

### ISSUE THREAD

**Issue by petrk94** [nickola/web-console#25]
Hello,

I want to open webconsole in a subdomain, but without typing in the URL the webconsole.php.
Example like its now:
webconsole.xxx.de/webconsole.php

Example how I want that it works:
webconsole.xxx.de/

Hope you can help me
thanks

**Comment by jcubic** [comment]
You can rename webconsole.php to index.php.

**Comment by petrk94** [comment]
Ah thank you very much^^
I didnt came on it. Thanks
