### ISSUE TITLE
Сontacts

### ISSUE THREAD

**Issue by morrouams** [nickola/web-console#58]
Николай, добрый день! 

Прошу прощения, что пришлось открыть ишью для того, чтобы выйти с вами на связь, но не получила ответ ни по одному контакту из вашего резюме с сайта, а здесь вижу, что есть активность. 
Меня зовут Диана, я рекрутер из Яндекса. Очень заинтересовал ваш профиль, хотела бы узнать, как обстоят ваши дела на текущий момент? Открыты ли к новым предложениям?
Для более оперативной связи со мной можно использовать тг: @dozmorovadv или почту: dozmorovadv@yandex-team.ru

Заранее спасибо за ответ!

**Comment by nickola** [comment]
Contacted by e-mail.
