### ISSUE TITLE
прошу прощения, не там открыл issue

### ISSUE THREAD

**Issue by bushuliak** [nickola/web-console#60]
прошу прощения, не там открыл issue

**Comment by Bushulyak** [comment]
![image](https://user-images.githubusercontent.com/26183062/121688403-176b9e00-cacc-11eb-9b8d-82b643814290.png)
![image](https://user-images.githubusercontent.com/26183062/121688441-22263300-cacc-11eb-86d5-bfd7783cf135.png)

**Comment by Bushulyak** [comment]
прошу прощения, не туда)
